---
title: "q2"
author: "Gaurav"
date: "11/4/2019"
output: html_document
---

```{r setup}
options(digits = 11)
```


```{r}
returnNbrs <- function(point,depthRemaining,n){
      minP <- sum(point == 0)
      maxP <- sum(point == (n-1))
      extP <- minP + maxP
      nNbr <- (length(point) - extP)*2 + extP
      minExists <- F
      maxExists <- F
      restExists <- F
      if(depthRemaining == 1) {return(nNbr)}
      if(minP != 0){ minExists = T; minP = which(point == 0)}
      if(maxP != 0){ maxExists = T;maxP = which(point == (n-1))}
      if(sum(union(minP,maxP) %in% 1:(length(point))) < length(point)){
            restExists <- T
            rest <- which(!(1:length(point) %in% union(minP,maxP)))
      }
      nbrs <- list()
      if(minExists){
            nb <- lapply(1:length(minP),function(x){
                  pt <- point
                  pt[minP[x]] <- 1
                  return(pt)
            })
             nbrs <- c(nbrs,nb)
      }
     
      if(maxExists){
            nb <- lapply(1:length(maxP),function(x){
                  pt <- point
                  pt[maxP[x]] <- n-2
                  return(pt)
            })
            nbrs <- c(nbrs,nb)
      }
      if(restExists){
            nb <- lapply(1:length(rest),function(x){
                  pt <- point
                  pt[rest[x]] <- pt[rest[x]] - 1
                  return(pt)
            })
            nb2 <- lapply(1:length(rest),function(x){
                  pt <- point
                  pt[rest[x]] <- pt[rest[x]] + 1
                  return(pt)
            })
            nbrs <- c(nbrs,nb,nb2)
      }
      return(nbrs)
}
```

```{r}
m <- matrix(ncol = n)

```


```{r}
numPaths <- function(point,depth,n){
      nbrs <- returnNbrs(point,depth,n)
      depth <- depth - 1
      paths <- 0
      if(depth == 1){
            pth <- sapply(nbrs, function(nb) { returnNbrs(nb,depth,n)})
            paths <- paths + sum(pth)
            return(paths)
      }else{
            pth <- sapply(nbrs,function(nb){
                  numPaths(nb,depth,n)
            })
            paths <- paths + sum(pth)
            return(paths)
      }
      
}
```

```{r}
point <- rep(0,4)
n = 10
m = 10
numPaths(point,m,n)
```
The least number of paths will be associated with the corner because the starting number 
of neigbors is the least, follwed by edges which have more number of neighbors than the corners but lesser than the points towards the center.
```{r}
point <- rep(4,4)
numPaths(point,m,n)
```

